### ISSUE TITLE
Cannot read property 'search' of undefined

### ISSUE THREAD

**Issue by kudsyf** [oferh/ng2-completer#169]
hi, am trying to inject a string Array to the completer service, but am getting this error 

> Cannot read property 'search' of undefined

in the constructor am getting array from firebase, then converted to string array then pass it to the completerService

```
  constructor(private completerService: CompleterService, private es: EditService) {

    this.es.getContents().subscribe(cnl => {
      var x = cnl.map(function (item) {
        return item['Name'];
      });
      console.log('x ', x, this.searchData);
      this.contentsList = completerService.local(x);
      console.log('contentsList 2', this.contentsList);

    });

  }
```

any idea why am getting this ?

**Comment by kudsyf** [comment]
solved with #37

**Comment by do-web** [comment]
I have also the same Problem Cannot read property 'search' of undefined.
#37 Does not solve the issue.

**Comment by oferh** [comment]
see issue #124
