### ISSUE TITLE
Error: ViewDestroyedError

### ISSUE THREAD

**Issue by msajnog** [oferh/ng2-completer#266]
Hi,
I have two completers in my component, second dependent on the first. Second is initially disabled, activates when I choose something from the first. And then, when I click on the second completer the list with records should be expanded but I've got following error:

`ERROR Error: Uncaught (in promise): Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:8835:12)
    at Object.debugUpdateDirectives [as updateDirectives] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12810:15)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12225:14)
    at callWithDebugContext (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12753:12)
    at ViewRef_.detectChanges (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10322:63)
    at CtrList.refreshTemplate (eval at <anonymous> (http://localhost:8000/app.js:1064:1), <anonymous>:187:26)
    at SafeSubscriber.eval [as _next] (eval at <anonymous> (http://localhost:8000/app.js:1064:1), <anonymous>:70:27)
    at SafeSubscriber.__tryOrUnsub (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:236:16)
    at SafeSubscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:185:22)
    at Subscriber._next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:125:26)
    at Subscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:89:18)
    at CatchSubscriber.Subscriber._next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:125:26)
    at CatchSubscriber.Subscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:89:18)
    at GetBranchName.Subject.next (eval at 6 (http://localhost:8000/vendor.js:1778:1), <anonymous>:55:25)
    at eval (eval at <anonymous> (http://localhost:8000/app.js:692:1), <anonymous>:65:19)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:381:26)
    at Object.onInvoke (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4331:37)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:380:32)
    at Zone.run (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:141:43)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:805:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:574:35)
    at XMLHttpRequest.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:480:25)
    at viewDestroyedError (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:8835:12)
    at Object.debugUpdateDirectives [as updateDirectives] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12810:15)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12225:14)
    at callWithDebugContext (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12753:12)
    at ViewRef_.detectChanges (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10322:63)
    at CtrList.refreshTemplate (eval at <anonymous> (http://localhost:8000/app.js:1064:1), <anonymous>:187:26)
    at SafeSubscriber.eval [as _next] (eval at <anonymous> (http://localhost:8000/app.js:1064:1), <anonymous>:70:27)
    at SafeSubscriber.__tryOrUnsub (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:236:16)
    at SafeSubscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:185:22)
    at Subscriber._next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:125:26)
    at Subscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:89:18)
    at CatchSubscriber.Subscriber._next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:125:26)
    at CatchSubscriber.Subscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:89:18)
    at GetBranchName.Subject.next (eval at 6 (http://localhost:8000/vendor.js:1778:1), <anonymous>:55:25)
    at eval (eval at <anonymous> (http://localhost:8000/app.js:692:1), <anonymous>:65:19)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:381:26)
    at Object.onInvoke (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4331:37)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:380:32)
    at Zone.run (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:141:43)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:805:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:574:35)
    at XMLHttpRequest.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:480:25)
    at resolvePromise (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:757:31)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:808:17)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:574:35)
    at XMLHttpRequest.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:480:25)
    at ____________________Elapsed_11_ms__At__Tue_Jun_27_2017_11_04_28_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3308:1), <anonymous>:109:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:290:29)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Zone.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:225:43)
    at Zone.scheduleMicroTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:245:25)
    at scheduleResolveOrReject (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:803:14)
    at resolvePromise (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:752:21)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:805:17)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:574:35)
    at XMLHttpRequest.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:480:25)
    at ____________________Elapsed_0_ms__At__Tue_Jun_27_2017_11_04_28_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3308:1), <anonymous>:109:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:290:29)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Zone.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:225:43)
    at Zone.scheduleMicroTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:245:25)
    at scheduleResolveOrReject (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:803:14)
    at resolvePromise (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:752:21)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:805:17)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:574:35)
    at XMLHttpRequest.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:480:25)
    at ____________________Elapsed_25_ms__At__Tue_Jun_27_2017_11_04_28_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3308:1), <anonymous>:109:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:290:29)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Zone.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:225:43)
    at Zone.scheduleMicroTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:245:25)
    at scheduleResolveOrReject (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:803:14)
    at resolvePromise (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:752:21)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:805:17)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:574:35)
    at XMLHttpRequest.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:480:25)
    at ____________________Elapsed_1_ms__At__Tue_Jun_27_2017_11_04_28_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3308:1), <anonymous>:109:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:290:29)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Zone.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:225:43)
    at Zone.scheduleMicroTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:245:25)
    at scheduleResolveOrReject (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:803:14)
    at resolvePromise (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:752:21)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:805:17)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:574:35)
    at XMLHttpRequest.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:480:25)
    at ____________________Elapsed_0_ms__At__Tue_Jun_27_2017_11_04_28_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3308:1), <anonymous>:109:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:290:29)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Zone.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:225:43)
    at Zone.scheduleMicroTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:245:25)
    at scheduleResolveOrReject (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:803:14)
    at resolvePromise (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:752:21)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:683:17)
    at SafeSubscriber.eval [as _complete] (eval at 1169 (http://localhost:8000/vendor.js:167:1), <anonymous>:68:122)
    at SafeSubscriber.__tryOrUnsub (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:236:16)
    at SafeSubscriber.complete (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:221:26)
    at Subscriber._complete (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:132:26)
    at Subscriber.complete (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:114:18)
    at CatchSubscriber.Subscriber._complete (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:132:26)
    at CatchSubscriber.Subscriber.complete (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:114:18)
    at MapSubscriber.Subscriber._complete (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:132:26)
    at MapSubscriber.Subscriber.complete (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:114:18)
    at XMLHttpRequest.onLoad (eval at 23 (http://localhost:8000/vendor.js:526:1), <anonymous>:1245:38)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at XMLHttpRequest.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:476:38)
    at ____________________Elapsed_168_ms__At__Tue_Jun_27_2017_11_04_28_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3308:1), <anonymous>:109:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:290:29)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Zone.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:225:43)
    at Zone.scheduleEventTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:251:25)
    at zoneAwareAddListener (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1255:14)
    at XMLHttpRequest.proto.(anonymous function) [as addEventListener] (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1402:20)
    at Observable.eval [as _subscribe] (eval at 23 (http://localhost:8000/vendor.js:526:1), <anonymous>:1290:18)
    at Observable._trySubscribe (eval at 0 (http://localhost:8000/vendor.js:7:1), <anonymous>:57:25)
    at Observable.subscribe (eval at 0 (http://localhost:8000/vendor.js:7:1), <anonymous>:45:27)
    at MapOperator.call (eval at 76 (http://localhost:8000/vendor.js:1834:1), <anonymous>:54:23)
    at Observable.subscribe (eval at 0 (http://localhost:8000/vendor.js:7:1), <anonymous>:42:22)
    at CatchOperator.call (eval at 456 (http://localhost:8000/vendor.js:1611:1), <anonymous>:79:23)
    at Observable.subscribe (eval at 0 (http://localhost:8000/vendor.js:7:1), <anonymous>:42:22)
    at eval (eval at 1169 (http://localhost:8000/vendor.js:167:1), <anonymous>:68:15)
    at new ZoneAwarePromise (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:821:29)
    at Observable.toPromise (eval at 1169 (http://localhost:8000/vendor.js:167:1), <anonymous>:66:12)
    at GenericHttpService.intercept (eval at <anonymous> (http://localhost:8000/app.js:152:1), <anonymous>:74:24)
    at GenericHttpService.post (eval at <anonymous> (http://localhost:8000/app.js:152:1), <anonymous>:62:21)
    at DictionariesHttpService.getBanksBranches (eval at <anonymous> (http://localhost:8000/app.js:227:1), <anonymous>:37:26)
    at DictionaryService.getBranchName (eval at <anonymous> (http://localhost:8000/app.js:437:1), <anonymous>:59:38)
    at GetBranchName.search (eval at <anonymous> (http://localhost:8000/app.js:692:1), <anonymous>:57:32)
    at CtrList.searchTimerComplete (eval at <anonymous> (http://localhost:8000/app.js:1064:1), <anonymous>:161:27)
    at SafeSubscriber.eval [as _next] (eval at <anonymous> (http://localhost:8000/app.js:1064:1), <anonymous>:117:23)
    at SafeSubscriber.__tryOrUnsub (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:236:16)
    at SafeSubscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:185:22)
    at Subscriber._next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:125:26)
    at Subscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:89:18)
    at AsyncAction.TimerObservable.dispatch (eval at <anonymous> (http://localhost:8000/app.js:4111:1), <anonymous>:87:20)
    at AsyncAction._execute (eval at 113 (http://localhost:8000/vendor.js:127:1), <anonymous>:111:18)
    at AsyncAction.execute (eval at 113 (http://localhost:8000/vendor.js:127:1), <anonymous>:86:26)
    at AsyncScheduler.flush (eval at 114 (http://localhost:8000/vendor.js:143:1), <anonymous>:36:32)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:476:38)
    at timer (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1491:29)
    at ____________________Elapsed_530_ms__At__Tue_Jun_27_2017_11_04_28_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3308:1), <anonymous>:109:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:290:29)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Zone.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:225:43)
    at Zone.scheduleMacroTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:248:25)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1527:33)
    at proto.(anonymous function) (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1402:20)
    at AsyncAction.requestAsyncId (eval at 113 (http://localhost:8000/vendor.js:127:1), <anonymous>:65:28)
    at AsyncAction.schedule (eval at 113 (http://localhost:8000/vendor.js:127:1), <anonymous>:60:35)
    at AsyncScheduler.Scheduler.schedule (eval at 956 (http://localhost:8000/vendor.js:1941:1), <anonymous>:43:53)
    at TimerObservable._subscribe (eval at <anonymous> (http://localhost:8000/app.js:4111:1), <anonymous>:100:26)
    at TimerObservable.Observable._trySubscribe (eval at 0 (http://localhost:8000/vendor.js:7:1), <anonymous>:57:25)
    at TimerObservable.Observable.subscribe (eval at 0 (http://localhost:8000/vendor.js:7:1), <anonymous>:45:27)
    at CtrList.search (eval at <anonymous> (http://localhost:8000/app.js:1064:1), <anonymous>:116:117)
    at CtrList.open (eval at <anonymous> (http://localhost:8000/app.js:1064:1), <anonymous>:136:18)
    at CtrCompleter.open (eval at <anonymous> (http://localhost:8000/app.js:192:1), <anonymous>:80:23)
    at CtrInput.onfocus (eval at <anonymous> (http://localhost:8000/app.js:1057:1), <anonymous>:143:28)
    at Object.eval [as handleEvent] (ng:///Ng2CompleterModule/CompleterCmp.ngfactory.js:631:43)
    at handleEvent (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12005:138)
    at callWithDebugContext (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13213:42)
    at Object.debugHandleEvent [as handleEvent] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12801:12)
    at dispatchEvent (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:8979:21)
    at eval (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:9569:38)
    at HTMLInputElement.eval (eval at 30 (http://localhost:8000/vendor.js:598:1), <anonymous>:2731:53)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at HTMLInputElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:476:38)
    at ____________________Elapsed_59539_ms__At__Tue_Jun_27_2017_11_03_28_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3308:1), <anonymous>:109:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:290:29)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Zone.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:225:43)
    at Zone.scheduleEventTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:251:25)
    at zoneAwareAddListener (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1255:14)
    at HTMLInputElement.proto.(anonymous function) [as addEventListener] (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1402:20)
    at DomEventsPlugin.addEventListener (eval at 30 (http://localhost:8000/vendor.js:598:1), <anonymous>:3131:17)
    at EventManager.addEventListener (eval at 30 (http://localhost:8000/vendor.js:598:1), <anonymous>:2477:23)
    at EmulatedEncapsulationDomRenderer2.DefaultDomRenderer2.listen (eval at 30 (http://localhost:8000/vendor.js:598:1), <anonymous>:2990:36)
    at DebugRenderer2.listen (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13477:30)
    at listenToElementOutputs (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:9558:66)
    at createViewNodes (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12149:17)
    at callViewAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12547:13)
    at execComponentViewsAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12486:13)
    at createViewNodes (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12204:5)
    at createEmbeddedView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12070:5)
    at callWithDebugContext (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13213:42)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12746:12)
    at TemplateRef_.createEmbeddedView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10408:38)
    at ViewContainerRef_.createEmbeddedView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10200:52)
    at NgIf._updateView (eval at 29 (http://localhost:8000/vendor.js:590:1), <anonymous>:2003:45)
    at NgIf.set [as ngIf] (eval at 29 (http://localhost:8000/vendor.js:590:1), <anonymous>:1962:18)
    at updateProp (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:11172:37)
    at checkAndUpdateDirectiveInline (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10869:19)
    at checkAndUpdateNodeInline (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12290:17)
    at checkAndUpdateNode (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12258:16)
    at debugCheckAndUpdateNode (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12887:59)
    at debugCheckDirectivesFn (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12828:13)
    at Object.eval [as updateDirectives] (ng:///OrderCommonModule/PolicyInfoComponent.ngfactory.js:8134:5)
    at Object.debugUpdateDirectives [as updateDirectives] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12813:21)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12225:14)
    at callViewAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12540:17)
    at execEmbeddedViewsAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12512:17)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12226:5)
    at callViewAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12540:17)
    at execComponentViewsAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12486:13)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12231:5)
    at callViewAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12540:17)
    at execComponentViewsAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12486:13)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12231:5)
    at callViewAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12540:17)
    at execEmbeddedViewsAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12512:17)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12226:5)
    at callViewAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12540:17)
    at execComponentViewsAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12486:13)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12231:5)
    at callViewAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12540:17)
    at execEmbeddedViewsAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12512:17)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12226:5)
    at callViewAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12540:17)
    at execComponentViewsAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12486:13)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12231:5)
    at callWithDebugContext (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12753:12)
    at ViewRef_.detectChanges (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10322:63)
    at eval (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:5258:63)
    at Array.forEach (native)
    at ApplicationRef_.tick (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:5258:25)
    at eval (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:5138:106)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:381:26)
    at Object.onInvoke (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4331:37)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:380:32)
    at Zone.run (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:141:43)
    at NgZone.run (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4200:62)
    at Object.next (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:5138:82)
    at SafeSubscriber.schedulerFn [as _next] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4034:52)
    at SafeSubscriber.__tryOrUnsub (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:236:16)
    at SafeSubscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:185:22)
    at Subscriber._next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:125:26)
    at Subscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:89:18)
    at EventEmitter.Subject.next (eval at 6 (http://localhost:8000/vendor.js:1778:1), <anonymous>:55:25)
    at EventEmitter.emit (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4020:76)
    at NgZone.checkStable (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4296:40)
    at NgZone.onLeave (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4372:14)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4325:27)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:476:38)
    at timer (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1491:29)
    at ____________________Elapsed_13_ms__At__Tue_Jun_27_2017_11_03_28_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3308:1), <anonymous>:109:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:290:29)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Zone.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:225:43)
    at Zone.scheduleMacroTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:248:25)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1527:33)
    at proto.(anonymous function) (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1402:20)
    at PolicyInfoComponent.onBankSelected (eval at <anonymous> (http://localhost:8000/app.js:1756:1), <anonymous>:241:9)
    at Object.eval [as handleEvent] (ng:///OrderCommonModule/PolicyInfoComponent.ngfactory.js:7049:24)
    at handleEvent (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12005:138)
    at callWithDebugContext (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13213:42)
    at Object.debugHandleEvent [as handleEvent] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12801:12)
    at dispatchEvent (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:8979:21)
    at eval (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10844:38)
    at SafeSubscriber.schedulerFn [as _next] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4046:36)
    at SafeSubscriber.__tryOrUnsub (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:236:16)
    at SafeSubscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:185:22)
    at Subscriber._next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:125:26)
    at Subscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:89:18)
    at EventEmitter.Subject.next (eval at 6 (http://localhost:8000/vendor.js:1778:1), <anonymous>:55:25)
    at EventEmitter.emit (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4020:76)
    at eval (eval at <anonymous> (http://localhost:8000/app.js:1043:1), <anonymous>:141:28)
    at SafeSubscriber.schedulerFn [as _next] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4046:36)
    at SafeSubscriber.__tryOrUnsub (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:236:16)
    at SafeSubscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:185:22)
    at Subscriber._next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:125:26)
    at Subscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:89:18)
    at EventEmitter.Subject.next (eval at 6 (http://localhost:8000/vendor.js:1778:1), <anonymous>:55:25)
    at EventEmitter.emit (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4020:76)
    at CtrCompleter.onSelected (eval at <anonymous> (http://localhost:8000/app.js:192:1), <anonymous>:26:23)
    at CtrDropdown.onSelected (eval at <anonymous> (http://localhost:8000/app.js:493:1), <anonymous>:104:24)
    at CtrRow.onClick (eval at <anonymous> (http://localhost:8000/app.js:1071:1), <anonymous>:34:23)
    at Object.eval [as handleEvent] (ng:///Ng2CompleterModule/CompleterCmp.ngfactory.js:176:42)
    at handleEvent (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12005:138)
    at callWithDebugContext (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13213:42)
    at Object.debugHandleEvent [as handleEvent] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12801:12)
    at dispatchEvent (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:8979:21)
    at eval (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:9569:38)
    at HTMLDivElement.eval (eval at 30 (http://localhost:8000/vendor.js:598:1), <anonymous>:2731:53)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at HTMLDivElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:476:38)
    at ____________________Elapsed_1509_ms__At__Tue_Jun_27_2017_11_03_27_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3308:1), <anonymous>:109:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:290:29)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:394:51)
    at Zone.scheduleTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:225:43)
    at Zone.scheduleEventTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:251:25)
    at zoneAwareAddListener (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1255:14)
    at HTMLDivElement.proto.(anonymous function) [as addEventListener] (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:1402:20)
    at DomEventsPlugin.addEventListener (eval at 30 (http://localhost:8000/vendor.js:598:1), <anonymous>:3131:17)
    at EventManager.addEventListener (eval at 30 (http://localhost:8000/vendor.js:598:1), <anonymous>:2477:23)
    at EmulatedEncapsulationDomRenderer2.DefaultDomRenderer2.listen (eval at 30 (http://localhost:8000/vendor.js:598:1), <anonymous>:2990:36)
    at DebugRenderer2.listen (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13477:30)
    at listenToElementOutputs (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:9558:66)
    at createViewNodes (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12149:17)
    at createEmbeddedView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12070:5)
    at callWithDebugContext (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13213:42)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12746:12)
    at TemplateRef_.createEmbeddedView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10408:38)
    at ViewContainerRef_.createEmbeddedView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10200:52)
    at eval (eval at 29 (http://localhost:8000/vendor.js:590:1), <anonymous>:1769:66)
    at DefaultIterableDiffer.forEachOperation (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:7198:17)
    at NgForOf._applyChanges (eval at 29 (http://localhost:8000/vendor.js:590:1), <anonymous>:1767:17)
    at NgForOf.ngDoCheck (eval at 29 (http://localhost:8000/vendor.js:590:1), <anonymous>:1757:22)
    at checkAndUpdateDirectiveInline (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10914:19)
    at checkAndUpdateNodeInline (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12290:17)
    at checkAndUpdateNode (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12258:16)
    at debugCheckAndUpdateNode (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12887:59)
    at debugCheckDirectivesFn (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12828:13)
    at Object.eval [as updateDirectives] (ng:///Ng2CompleterModule/CompleterCmp.ngfactory.js:377:5)
    at Object.debugUpdateDirectives [as updateDirectives] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12813:21)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12225:14)
    at callViewAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12540:17)
    at execEmbeddedViewsAction (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12512:17)
    at checkAndUpdateView (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12226:5)
    at callWithDebugContext (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:12753:12)
    at ViewRef_.detectChanges (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:10322:63)
    at CtrList.refreshTemplate (eval at <anonymous> (http://localhost:8000/app.js:1064:1), <anonymous>:187:26)
    at SafeSubscriber.eval [as _next] (eval at <anonymous> (http://localhost:8000/app.js:1064:1), <anonymous>:70:27)
    at SafeSubscriber.__tryOrUnsub (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:236:16)
    at SafeSubscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:185:22)
    at Subscriber._next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:125:26)
    at Subscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:89:18)
    at CatchSubscriber.Subscriber._next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:125:26)
    at CatchSubscriber.Subscriber.next (eval at 5 (http://localhost:8000/vendor.js:1706:1), <anonymous>:89:18)
    at GetBankName.Subject.next (eval at 6 (http://localhost:8000/vendor.js:1778:1), <anonymous>:55:25)
    at eval (eval at <anonymous> (http://localhost:8000/app.js:692:1), <anonymous>:31:19)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:381:26)
    at Object.onInvoke (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4331:37)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:380:32)
    at Zone.run (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:141:43)
    at eval (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:805:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:414:31)
    at Object.onInvokeTask (eval at 1 (http://localhost:8000/vendor.js:15:1), <anonymous>:4322:37)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:413:36)
    at Zone.runTask (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:181:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:574:35)
    at XMLHttpRequest.ZoneTask.invoke (eval at <anonymous> (http://localhost:8000/polyfills.js:3314:1), <anonymous>:480:25)`

**Comment by vdurante** [comment]
I have the same issue when my `ng2-completer` gets disabled and re-enabled later due to a *ngIf change.

I am also changing my CompleterData based on these changes.

**Comment by oferh** [comment]
should  be fixed in 1.6.0 see this [demo](https://embed.plnkr.co/fmDvpV/)

**Comment by szh** [comment]
I'm still getting a ViewDestroyedError with 1.6.0 in some cases.

```
Unhandled exception: Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (webpack:///./~/@angular/core/bundles/core.umd.js?:8535:12)
    at Object.debugUpdateDirectives [as updateDirectives] (webpack:///./~/@angular/core/bundles/core.umd.js?:13135:15)
    at checkAndUpdateView (webpack:///./~/@angular/core/bundles/core.umd.js?:12320:14)
    at callWithDebugContext (webpack:///./~/@angular/core/bundles/core.umd.js?:13538:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (webpack:///./~/@angular/core/bundles/core.umd.js?:13078:12)
    at ViewRef_.detectChanges (webpack:///./~/@angular/core/bundles/core.umd.js?:10259:18)
    at t.refreshTemplate (webpack:///./~/ng2-completer/ng2-completer.umd.js?:1:28916)
    at SafeSubscriber.eval [as _next] (webpack:///./~/ng2-completer/ng2-completer.umd.js?:1:30057)
    at SafeSubscriber.__tryOrUnsub (webpack:///./~/rxjs/Subscriber.js?:238:16)
    at SafeSubscriber.next (webpack:///./~/rxjs/Subscriber.js?:185:22)
    at Subscriber._next (webpack:///./~/rxjs/Subscriber.js?:125:26)
    at Subscriber.next (webpack:///./~/rxjs/Subscriber.js?:89:18)
    at CatchSubscriber.Subscriber._next (webpack:///./~/rxjs/Subscriber.js?:125:26)
    at CatchSubscriber.Subscriber.next (webpack:///./~/rxjs/Subscriber.js?:89:18)
...
```

**Comment by oferh** [comment]
can you create a plunker or a repo that reproduces the error?

**Comment by szh** [comment]
When I call `enableProdMode()`, I no longer get this exception. I had the idea to try that because the stack trace is full of references to `detectChanges`, which happens twice in dev mode (to ensure there are no side effects of change detection). So that makes this a lower priority.
